# .github/labels.yml
- name: Added
  description: Add new features.
  color: "0e8a16"
- name: Changed
  description: Change existing functionality.
  color: "fbca04"
- name: Deprecated
  description: Mark as soon-to-be removed features.
  color: "d93f0b"
- name: Fixed
  description: Remove features.
  color: "b60205"
- name: Security
  description: Fix bug.
  color: "5319e7"
- name: Others
  description: In case of vulnerabilities.
  color: "0052cc"